name: Sync Yuque

on: 
  workflow_dispatch: 
  schedule: 
    # 北京时间每日2点和14点准时执行
    - cron: "0 6,18 * * *"

jobs: 
  sync-yuque: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x

    - name: Set Timezone and Install pnpm
      run: |
        export TZ='Asia/Shanghai'
        npm install -g pnpm

    - name: Install dependencies
      run: |
        export TZ='Asia/Shanghai'
        pnpm install --prod

    - name: Pull Yuque articles
      env:
        YUQUE_USERNAME: ${{ secrets.YUQUE_USERNAME }}
        YUQUE_PASSWORD: ${{ secrets.YUQUE_PASSWORD }}
        YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
        YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_HOST: ${{ secrets.COS_HOST }}
      run: |
        pnpm sync

    - name: Configure Git user
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
        git add .
        git commit -m "Update documents" -a

    - name: Push changes to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        repository: nscc-neuro/nest-guide
        force: true